"use client";
import {ChangeEvent,useMemo,useState} from "react";
import Link from "next/link";
import * as XLSX from "xlsx";
import {ArrowLeft,CheckCircle2,Download,FileSpreadsheet,Upload,XCircle} from "lucide-react";
import AuthGuard from "@/components/AuthGuard";
import AppShell from "@/components/AppShell";
import Notice from "@/components/Notice";
import {supabase} from "@/lib/supabase";
import type {Product} from "@/lib/types";
type ImportRow={rowNumber:number;sku:string;name:string;light_color:string;unit:string;price:number;stock:number;status:"new"|"update"|"error";message:string;existingId?:string};
const normalize=(v:unknown)=>String(v??"").trim();
const normalizeKey=(sku:string,name:string)=>`${sku.trim().toUpperCase()}__${name.trim().toLowerCase()}`;
const toNumber=(v:unknown)=>{if(typeof v==="number")return Number.isFinite(v)?v:0;const n=Number(String(v??"").replace(/[^0-9.-]/g,""));return Number.isFinite(n)?n:0};
const findHeaderRow=(rows:unknown[][])=>rows.findIndex(row=>row.some(cell=>normalize(cell).toLowerCase().includes("mã sản phẩm")));
function pick(record:Record<string,unknown>,aliases:string[]){const key=Object.keys(record).find(k=>aliases.includes(k.trim().toLowerCase()));return key?record[key]:undefined}
export default function ProductImportPage(){
 const[rows,setRows]=useState<ImportRow[]>([]),[fileName,setFileName]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[isError,setIsError]=useState(false);
 const summary=useMemo(()=>({total:rows.length,valid:rows.filter(r=>r.status!=="error").length,added:rows.filter(r=>r.status==="new").length,updated:rows.filter(r=>r.status==="update").length,errors:rows.filter(r=>r.status==="error").length}),[rows]);
 async function readFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setBusy(true);setMessage("");setFileName(file.name);try{const buffer=await file.arrayBuffer();const workbook=XLSX.read(buffer,{type:"array"});const worksheet=workbook.Sheets[workbook.SheetNames[0]];const rawRows=XLSX.utils.sheet_to_json<unknown[]>(worksheet,{header:1,defval:""});const headerIndex=findHeaderRow(rawRows);if(headerIndex<0)throw new Error("Không tìm thấy dòng tiêu đề “Mã sản phẩm”. Hãy dùng đúng file Excel mẫu.");const headers=rawRows[headerIndex].map(normalize);const objects=rawRows.slice(headerIndex+1).filter(row=>row.some(cell=>normalize(cell)!=="")).map(row=>Object.fromEntries(headers.map((header,index)=>[header,row[index]])));const{data:products,error}=await supabase.from("products").select("*");if(error)throw error;const productList=(products||[]) as Product[];const existingMap=new Map(productList.map(p=>[normalizeKey(p.sku,p.name),p]));const seen=new Set<string>();const parsed:ImportRow[]=objects.map((record,index)=>{const sku=normalize(pick(record,["mã sản phẩm","mã sp","sku"])).toUpperCase();const name=normalize(pick(record,["tên sản phẩm","tên sp","name"]));const light_color=normalize(pick(record,["ánh sáng","màu ánh sáng","light_color","light color"]));const unit=normalize(pick(record,["đơn vị","đvt","unit"]))||"Cái";const price=Math.max(0,toNumber(pick(record,["giá bán","giá","price"])));const stock=Math.max(0,Math.floor(toNumber(pick(record,["tồn kho","tồn","stock"]))));const key=normalizeKey(sku,name),rowNumber=headerIndex+index+2;if(!sku||!name)return{rowNumber,sku,name,light_color,unit,price,stock,status:"error",message:"Thiếu mã hoặc tên sản phẩm"};if(seen.has(key))return{rowNumber,sku,name,light_color,unit,price,stock,status:"error",message:"Trùng Mã + Tên ngay trong file Excel"};seen.add(key);const existing=existingMap.get(key);return{rowNumber,sku,name,light_color,unit,price,stock,status:existing?"update":"new",message:existing?"Cập nhật ánh sáng, giá, đơn vị và tồn kho":"Thêm mới",existingId:existing?.id}});setRows(parsed);setIsError(false);setMessage(`Đã đọc ${parsed.length} dòng từ ${file.name}`)}catch(error){setRows([]);setIsError(true);setMessage(error instanceof Error?error.message:"Không thể đọc file Excel")}finally{setBusy(false);event.target.value=""}}
 async function importProducts(){const valid=rows.filter(r=>r.status!=="error");if(!valid.length)return;setBusy(true);setMessage("");try{const inserts=valid.filter(r=>r.status==="new").map(({sku,name,light_color,unit,price,stock})=>({sku,name,light_color:light_color||null,unit,price,stock}));const updates=valid.filter(r=>r.status==="update"&&r.existingId);for(let i=0;i<inserts.length;i+=300){const{error}=await supabase.from("products").insert(inserts.slice(i,i+300));if(error)throw error}for(let i=0;i<updates.length;i+=50){const results=await Promise.all(updates.slice(i,i+50).map(r=>supabase.from("products").update({sku:r.sku,name:r.name,light_color:r.light_color||null,unit:r.unit,price:r.price,stock:r.stock}).eq("id",r.existingId!)));const failed=results.find(x=>x.error);if(failed?.error)throw failed.error}setIsError(false);setMessage(`Hoàn tất: thêm mới ${inserts.length}, cập nhật ${updates.length} sản phẩm.`);setRows([]);setFileName("")}catch(error){setIsError(true);setMessage(error instanceof Error?error.message:"Không thể nhập dữ liệu")}finally{setBusy(false)}}
 return <AuthGuard><AppShell title="Nhập sản phẩm từ Excel" subtitle="Thêm mới hoặc cập nhật hàng loạt theo Mã sản phẩm + Tên sản phẩm" action={<Link href="/products" className="secondary inline"><ArrowLeft size={18}/>Quay lại</Link>}><div className="panel import-hero"><div><span className="eyebrow">VH LIGHTING DATA IMPORT</span><h2>Nhập hàng trăm sản phẩm trong một lần</h2><p>Tải mẫu, điền dữ liệu, chọn file và kiểm tra bản xem trước trước khi nhập.</p></div><a className="primary inline" href="/VH-Lighting-Mau-Nhap-San-Pham.xlsx" download><Download size={18}/>Tải Excel mẫu</a></div><Notice text={message} type={isError?"error":"ok"}/><div className="panel"><label className={`excel-dropzone ${busy?"disabled":""}`}><input type="file" accept=".xlsx,.xls" onChange={readFile} disabled={busy}/><FileSpreadsheet size={38}/><b>{fileName||"Chọn file Excel sản phẩm"}</b><span>Hỗ trợ .xlsx và .xls · dùng đúng file mẫu để tránh sai cột</span><span className="secondary inline"><Upload size={17}/>{busy?"Đang đọc…":"Chọn file"}</span></label></div>{rows.length>0&&<><div className="import-summary-grid"><article><span>Tổng dòng</span><b>{summary.total}</b></article><article className="success"><span>Thêm mới</span><b>{summary.added}</b></article><article className="warning"><span>Cập nhật</span><b>{summary.updated}</b></article><article className={summary.errors?"danger":""}><span>Lỗi</span><b>{summary.errors}</b></article></div><div className="panel"><div className="panel-heading"><div><h2>Xem trước dữ liệu</h2><p>Chỉ các dòng hợp lệ mới được nhập.</p></div><button className="primary inline" onClick={importProducts} disabled={busy||summary.valid===0}><CheckCircle2 size={18}/>{busy?"Đang nhập…":`Nhập ${summary.valid} sản phẩm`}</button></div><div className="table-wrap import-preview"><table className="data-table"><thead><tr><th>Dòng</th><th>Trạng thái</th><th>Mã</th><th>Tên sản phẩm</th><th>Ánh sáng</th><th>ĐVT</th><th className="align-right">Giá bán</th><th className="align-center">Tồn</th><th>Ghi chú</th></tr></thead><tbody>{rows.map(r=><tr key={`${r.rowNumber}-${r.sku}-${r.name}`} className={r.status==="error"?"row-error":""}><td>{r.rowNumber}</td><td>{r.status==="new"?<span className="status success-status">Thêm mới</span>:r.status==="update"?<span className="status warning-status">Cập nhật</span>:<span className="status danger-status"><XCircle size={13}/>Lỗi</span>}</td><td><span className="sku-pill">{r.sku||"—"}</span></td><td><b>{r.name||"—"}</b></td><td>{r.light_color||"—"}</td><td>{r.unit}</td><td className="align-right">{r.price.toLocaleString("vi-VN")} ₫</td><td className="align-center">{r.stock}</td><td>{r.message}</td></tr>)}</tbody></table></div></div></>}</AppShell></AuthGuard>
}
